services:
  - type: web
    name: insurance-premium-analytics
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn dashboard_lite:server --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --max-requests 1000 --max-requests-jitter 100"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: WEB_CONCURRENCY
        value: "1"
    autoDeploy: true
    plan: free  # Using the free tier